# -*- coding: utf-8 -*-
"""Generate the hero's expression overlays into src/art/faces.js.

The hero is drawn through the paper doll, which re-bakes the whole body every
time the armour changes. Baking a copy of every pose for every mood on top of
that would multiply the cache for no real gain, so a mood is instead a small
overlay stamped over the face after the body is drawn.

The overlay covers art rows 8..15 of the head -- the band where the face
interior is a constant 14 columns wide (cols 5..18) -- so it repaints the eyes
and mouth without ever touching the hair or the outline. Skin letters are not
remapped by the paper doll, so one overlay is correct for every armour set.
"""
import io
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "src", "art", "faces.js")

PAD = 5          # transparent columns either side of the 14-wide face interior


def face(rows):
    """Centre a 14-wide face band inside the hero's 24-wide art grid."""
    out = []
    for r in rows:
        assert len(r) == 14, "face row must be 14 wide, got %d: %r" % (len(r), r)
        out.append('.' * PAD + r + '.' * PAD)
    assert len(out) == 8, "face needs 8 rows, got %d" % len(out)
    return out


MOODS = {
    # Teeth bared, brows driven down and in.
    'attack': face([
        'ukkkUUUUUUkkku',
        'uUkkkUUUUkkkUu',
        'uUUkkUUUUkkUUu',
        'uUUkkUUUUkkUUu',
        'uUUUUUUUUUUUUu',
        'uUUUUkkkkUUUUu',
        'umUUkkkkkkUUmu',
        'umUUkRRRRkUUmu',
    ]),
    # Eyes screwed into crosses, mouth open in a wail.
    'hurt': face([
        'uUUUUUUUUUUUUu',
        'uUkUkUUUUkUkUu',
        'uUUkUUUUUUkUUu',
        'uUkUkUUUUkUkUu',
        'uUUUUUUUUUUUUu',
        'uUUUkkkkkkUUUu',
        'umUUkkkkkkUUmu',
        'umUUUkkkkUUUmu',
    ]),
    # Narrowed, holding a charge.
    'charge': face([
        'uUUUUUUUUUUUUu',
        'ukkkUUUUUUkkku',
        'uUkkkUUUUkkkUu',
        'uUkkkUUUUkkkUu',
        'uUUUUUUUUUUUUu',
        'uUUUUUUUUUUUUu',
        'umUUUkkkkUUUmu',
        'umUUUUUUUUUUmu',
    ]),
    # Wide eyes and a small round mouth while airborne.
    'air': face([
        'uUUUUUUUUUUUUu',
        'uUkkkUUUUkkkUu',
        'uUkWkUUUUkWkUu',
        'uUkkkUUUUkkkUu',
        'uUUUUUUUUUUUUu',
        'uUUUUUkkUUUUUu',
        'umUUUkkkkUUUmu',
        'umUUUUkkUUUUmu',
    ]),
    # Eyes shut into happy arcs, broad smile.
    'happy': face([
        'uUUUUUUUUUUUUu',
        'uUUkUUUUUUkUUu',
        'uUkUkUUUUkUkUu',
        'uUUUUUUUUUUUUu',
        'uUUUUUUUUUUUUu',
        'umUkUUUUUUkUmu',
        'umUUkkkkkkUUmu',
        'umUUUUUUUUUUmu',
    ]),
}

ORDER = ['attack', 'hurt', 'charge', 'air', 'happy']

TEMPLATE = '''/* Hero expression overlays.

   A mood is a small patch stamped over the face after the body is drawn, not a
   separate copy of every pose: the paper doll re-bakes the whole hero whenever
   the armour changes, so baking pose x mood would multiply that cache for no
   visual gain. The patch covers art rows 8..15 of the head, where the face
   interior is a constant 14 columns wide, so it never touches the hair or the
   outline. Skin letters are not remapped by the doll, which is why a single
   overlay is correct for every armour set.

   Generated by tools/art/faces.py -- edit the generator, not this file. */
window.DS = window.DS || {};

(function (DS) {
  'use strict';

  const A = DS.Art;

  /* Where the overlay sits relative to the hero sprite's own origin, in
     LOGICAL units: art row 8 of a 2x-detail sprite is 4 logical pixels down. */
  const FACE_OX = 0;
  const FACE_OY = 4;
  const FACE_D = 2;

  const ROWS = {
%s  };

  const baked = {};
  for (const key in ROWS) {
    if (Object.prototype.hasOwnProperty.call(ROWS, key)) {
      baked[key] = A.makeSprite(ROWS[key], null, FACE_D);
    }
  }

  const flipped = {};
  for (const key in baked) {
    if (Object.prototype.hasOwnProperty.call(baked, key)) {
      flipped[key] = A.flipped(baked[key]);
    }
  }

  DS.Faces = {
    OX: FACE_OX,
    OY: FACE_OY,
    rows: ROWS,
    hero: baked,
    heroFlip: flipped,

    /* Pick a mood from the player's current state. Returns null for the
       resting face, which is already baked into the body art. */
    moodFor: function (p) {
      if (p.dead) return 'hurt';
      if (p.hurtFace > 0) return 'hurt';
      if (p.charging) return 'charge';
      if (p.attackActive > 0 || p.swingTimer > 0) return 'attack';
      if (p.dashFrames > 0) return 'attack';
      if (!p.onGround) return 'air';
      return null;
    }
  };
})(window.DS);
'''


def main():
    blocks = []
    for key in ORDER:
        rows = MOODS[key]
        body = ",\n".join("      '%s'" % r for r in rows)
        blocks.append("    %s: [\n%s\n    ],\n" % (key, body))
    io.open(OUT, "w", encoding="utf-8").write(TEMPLATE % "".join(blocks))
    print("wrote", os.path.relpath(OUT, ROOT), "-", len(ORDER), "moods")


if __name__ == "__main__":
    main()
