# -*- coding: utf-8 -*-
"""Generate the elemental particle shapes into src/art/fxart.js.

Every effect in the game used to be the same square dot in a different colour,
so fire, poison and earth all read identically once they were in motion. These
are small shapes with silhouettes you can name at a glance -- a flame licks, a
shard is angular, a bubble is round with a highlight, a leaf has a stem -- and
the emitters in elements.js give each one the motion that matches it.

Shapes are authored at 2x detail like the rest of the art, and baked once per
element tint at load time.
"""
import io
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "src", "art", "fxart.js")

# Palette letters used by every shape below, so one tint table recolours them
# all: A = brightest core, B = mid, C = deep/edge.
SHAPES = {
    # A licking flame: broad base, tapering tip that leans.
    'flame': [
        '...AA...',
        '..AAAA..',
        '.AABBAA.',
        '.ABBBBA.',
        'ABBBBBBA',
        'ABBCCBBA',
        'ABCCCCBA',
        'ABCCCCBA',
        '.BCCCCB.',
        '.BCCCCB.',
        '..CCCC..',
        '...CC...',
    ],
    # An angular ice shard.
    'shard': [
        '...AA...',
        '..AABB..',
        '..ABBB..',
        '.AABBBB.',
        '.ABBBCB.',
        '.ABBBCB.',
        '.ABBCCB.',
        '..BBCC..',
        '..BCCC..',
        '...CC...',
    ],
    # A round bubble with a highlight on the upper left.
    'bubble': [
        '..CCCC..',
        '.CBBBBC.',
        'CBAABBBC',
        'CBAABBBC',
        'CBBBBBBC',
        'CBBBBBBC',
        '.CBBBBC.',
        '..CCCC..',
    ],
    # A falling droplet: round belly, pointed top.
    'droplet': [
        '..AA..',
        '..AA..',
        '.ABBA.',
        '.ABBA.',
        'ABBBBA',
        'ABBCBA',
        '.BCCB.',
        '..CC..',
    ],
    # A chunky rock fragment.
    'rock': [
        '.AAAA...',
        'ABBBBAA.',
        'ABBBBBBA',
        'ABBCBBBA',
        'ABCCBBBA',
        'ACCCBBA.',
        '.CCCCA..',
        '..CCC...',
    ],
    # A leaf with a stem, so it reads even while it tumbles.
    'leaf': [
        '.....AA...',
        '...AAAAA..',
        '..AABBBAA.',
        '.AABBBBBA.',
        'AABBBBBBA.',
        '.ABBBBBA..',
        '..CBBBA...',
        '...CCA....',
    ],
    # A jagged bolt, drawn vertical and rotated by the emitter.
    'bolt': [
        '..AA..',
        '..AA..',
        '.AAB..',
        '.ABB..',
        'AABB..',
        '.ABBB.',
        '..BBBA',
        '..BBAA',
        '..BBA.',
        '..CBA.',
        '..CB..',
        '.CC...',
        '.CC...',
        '.C....',
    ],
    # A four-point spark for hits and lightning crackle.
    'spark': [
        '..A...A.',
        '...A.A..',
        '.AAAAAA.',
        '..AABB..',
        '..ABBA..',
        '.AABBAA.',
        '..A.A...',
        '.A...A..',
    ],
}

# Per element: bright core, mid body, deep edge.
TINTS = {
    'fire':      ('#fff0a8', '#e8743b', '#8a3b2a'),
    'ice':       ('#ffffff', '#a8e4ff', '#2f6fa8'),
    'lightning': ('#ffffff', '#fff0a8', '#f2c14e'),
    'poison':    ('#a3e86b', '#5cbf62', '#1b4436'),
    'water':     ('#a8e4ff', '#4fb3e0', '#16324f'),
    'earth':     ('#b98d5c', '#8a6340', '#2e2018'),
    'leaf':      ('#a3e86b', '#2f7d4f', '#1b4436'),
    'dark':      ('#c86ee0', '#7f45b8', '#1e0f2a'),
    'holy':      ('#ffffff', '#fff0a8', '#8a7440'),
}

TEMPLATE = '''/* Elemental particle shapes.

   Every effect used to be the same square dot in a different colour, so fire,
   poison and earth all read identically once they were moving. These are small
   named silhouettes -- a flame licks, a shard is angular, a bubble is round
   with a highlight, a leaf has a stem -- and the emitters in elements.js pair
   each one with motion that matches it.

   Authored at 2x detail. `DS.FXArt.get(shape, element)` returns a baked sprite;
   everything is built once at load, so the render loop never bakes.

   Generated by tools/art/fx.py -- edit the generator, not this file. */
window.DS = window.DS || {};

(function (DS) {
  'use strict';

  const A = DS.Art;
  const FX_D = 2;

  const SHAPES = {
%s  };

  /* Bright core, mid body, deep edge -- the three letters every shape uses. */
  const TINTS = {
%s  };

  const cache = {};

  function get(shape, element) {
    const rows = SHAPES[shape];
    if (!rows) return null;
    const tint = TINTS[element] || TINTS.fire;
    const key = shape + ':' + (TINTS[element] ? element : 'fire');
    if (!cache[key]) {
      cache[key] = A.makeSprite(rows, { A: tint[0], B: tint[1], C: tint[2] }, FX_D);
    }
    return cache[key];
  }

  DS.FXArt = {
    D: FX_D,
    shapes: SHAPES,
    tints: TINTS,
    get: get,
    has: function (shape) { return !!SHAPES[shape]; }
  };
})(window.DS);
'''


def main():
    shape_js = []
    for name, rows in SHAPES.items():
        w = len(rows[0])
        for r in rows:
            assert len(r) == w, "%s: ragged row %r" % (name, r)
        body = ",\n".join("      '%s'" % r for r in rows)
        shape_js.append("    %s: [\n%s\n    ],\n" % (name, body))
        print("%-8s %dx%d -> %sx%s logical" % (name, w, len(rows), w / 2.0, len(rows) / 2.0))

    tint_js = []
    for name, (a, b, c) in TINTS.items():
        tint_js.append("    %s: ['%s', '%s', '%s'],\n" % (name, a, b, c))

    io.open(OUT, "w", encoding="utf-8").write(
        TEMPLATE % ("".join(shape_js), "".join(tint_js)))
    print("wrote", os.path.relpath(OUT, ROOT))


if __name__ == "__main__":
    main()
