/* Hero expression overlays.

   A mood is a small patch stamped over the face after the body is drawn, not a
   separate copy of every pose: the paper doll re-bakes the whole hero whenever
   the armour changes, so baking pose x mood would multiply that cache for no
   visual gain. The patch covers art rows 8..15 of the head, where the face
   interior is a constant 14 columns wide, so it never touches the hair or the
   outline. Skin letters are not remapped by the doll, which is why a single
   overlay is correct for every armour set.

   Generated by tools/art/faces.py -- edit the generator, not this file. */
window.DS = window.DS || {};

(function (DS) {
  'use strict';

  const A = DS.Art;

  /* Where the overlay sits relative to the hero sprite's own origin, in
     LOGICAL units: art row 8 of a 2x-detail sprite is 4 logical pixels down. */
  const FACE_OX = 0;
  const FACE_OY = 4;
  const FACE_D = 2;

  const ROWS = {
    attack: [
      '.....ukkkUUUUUUkkku.....',
      '.....uUkkkUUUUkkkUu.....',
      '.....uUUkkUUUUkkUUu.....',
      '.....uUUkkUUUUkkUUu.....',
      '.....uUUUUUUUUUUUUu.....',
      '.....uUUUUkkkkUUUUu.....',
      '.....umUUkkkkkkUUmu.....',
      '.....umUUkRRRRkUUmu.....'
    ],
    hurt: [
      '.....uUUUUUUUUUUUUu.....',
      '.....uUkUkUUUUkUkUu.....',
      '.....uUUkUUUUUUkUUu.....',
      '.....uUkUkUUUUkUkUu.....',
      '.....uUUUUUUUUUUUUu.....',
      '.....uUUUkkkkkkUUUu.....',
      '.....umUUkkkkkkUUmu.....',
      '.....umUUUkkkkUUUmu.....'
    ],
    charge: [
      '.....uUUUUUUUUUUUUu.....',
      '.....ukkkUUUUUUkkku.....',
      '.....uUkkkUUUUkkkUu.....',
      '.....uUkkkUUUUkkkUu.....',
      '.....uUUUUUUUUUUUUu.....',
      '.....uUUUUUUUUUUUUu.....',
      '.....umUUUkkkkUUUmu.....',
      '.....umUUUUUUUUUUmu.....'
    ],
    air: [
      '.....uUUUUUUUUUUUUu.....',
      '.....uUkkkUUUUkkkUu.....',
      '.....uUkWkUUUUkWkUu.....',
      '.....uUkkkUUUUkkkUu.....',
      '.....uUUUUUUUUUUUUu.....',
      '.....uUUUUUkkUUUUUu.....',
      '.....umUUUkkkkUUUmu.....',
      '.....umUUUUkkUUUUmu.....'
    ],
    happy: [
      '.....uUUUUUUUUUUUUu.....',
      '.....uUUkUUUUUUkUUu.....',
      '.....uUkUkUUUUkUkUu.....',
      '.....uUUUUUUUUUUUUu.....',
      '.....uUUUUUUUUUUUUu.....',
      '.....umUkUUUUUUkUmu.....',
      '.....umUUkkkkkkUUmu.....',
      '.....umUUUUUUUUUUmu.....'
    ],
  };

  const baked = {};
  for (const key in ROWS) {
    if (Object.prototype.hasOwnProperty.call(ROWS, key)) {
      baked[key] = A.makeSprite(ROWS[key], null, FACE_D);
    }
  }

  const flipped = {};
  for (const key in baked) {
    if (Object.prototype.hasOwnProperty.call(baked, key)) {
      flipped[key] = A.flipped(baked[key]);
    }
  }

  DS.Faces = {
    OX: FACE_OX,
    OY: FACE_OY,
    rows: ROWS,
    hero: baked,
    heroFlip: flipped,

    /* Pick a mood from the player's current state. Returns null for the
       resting face, which is already baked into the body art. */
    moodFor: function (p) {
      if (p.dead) return 'hurt';
      if (p.hurtFace > 0) return 'hurt';
      if (p.charging) return 'charge';
      if (p.attackActive > 0 || p.swingTimer > 0) return 'attack';
      if (p.dashFrames > 0) return 'attack';
      if (!p.onGround) return 'air';
      return null;
    }
  };
})(window.DS);
