/* Elemental particle shapes.

   Every effect used to be the same square dot in a different colour, so fire,
   poison and earth all read identically once they were moving. These are small
   named silhouettes -- a flame licks, a shard is angular, a bubble is round
   with a highlight, a leaf has a stem -- and the emitters in elements.js pair
   each one with motion that matches it.

   Authored at 2x detail. `DS.FXArt.get(shape, element)` returns a baked sprite;
   everything is built once at load, so the render loop never bakes.

   Generated by tools/art/fx.py -- edit the generator, not this file. */
window.DS = window.DS || {};

(function (DS) {
  'use strict';

  const A = DS.Art;
  const FX_D = 2;

  const SHAPES = {
    flame: [
      '...AA...',
      '..AAAA..',
      '.AABBAA.',
      '.ABBBBA.',
      'ABBBBBBA',
      'ABBCCBBA',
      'ABCCCCBA',
      'ABCCCCBA',
      '.BCCCCB.',
      '.BCCCCB.',
      '..CCCC..',
      '...CC...'
    ],
    shard: [
      '...AA...',
      '..AABB..',
      '..ABBB..',
      '.AABBBB.',
      '.ABBBCB.',
      '.ABBBCB.',
      '.ABBCCB.',
      '..BBCC..',
      '..BCCC..',
      '...CC...'
    ],
    bubble: [
      '..CCCC..',
      '.CBBBBC.',
      'CBAABBBC',
      'CBAABBBC',
      'CBBBBBBC',
      'CBBBBBBC',
      '.CBBBBC.',
      '..CCCC..'
    ],
    droplet: [
      '..AA..',
      '..AA..',
      '.ABBA.',
      '.ABBA.',
      'ABBBBA',
      'ABBCBA',
      '.BCCB.',
      '..CC..'
    ],
    rock: [
      '.AAAA...',
      'ABBBBAA.',
      'ABBBBBBA',
      'ABBCBBBA',
      'ABCCBBBA',
      'ACCCBBA.',
      '.CCCCA..',
      '..CCC...'
    ],
    leaf: [
      '.....AA...',
      '...AAAAA..',
      '..AABBBAA.',
      '.AABBBBBA.',
      'AABBBBBBA.',
      '.ABBBBBA..',
      '..CBBBA...',
      '...CCA....'
    ],
    bolt: [
      '..AA..',
      '..AA..',
      '.AAB..',
      '.ABB..',
      'AABB..',
      '.ABBB.',
      '..BBBA',
      '..BBAA',
      '..BBA.',
      '..CBA.',
      '..CB..',
      '.CC...',
      '.CC...',
      '.C....'
    ],
    spark: [
      '..A...A.',
      '...A.A..',
      '.AAAAAA.',
      '..AABB..',
      '..ABBA..',
      '.AABBAA.',
      '..A.A...',
      '.A...A..'
    ],
    star: [
      '...AA...',
      '..AAAA..',
      '..ABBA..',
      'AAAAA.AA',
      'ABBBBA.A',
      '..BBA...',
      '.AABBA..',
      'A..A..A.'
    ],
    heart: [
      '.AA..AA.',
      'AABBAABB',
      'ABBBBBAA',
      'ABBBBBA.',
      '.ABBBBA.',
      '..ABBA..',
      '...AA...',
      '........'
    ],
    pop: [
      'A..A..A.',
      '.A...A..',
      '..ABA...',
      'A..B..A.',
      '.ABBA...',
      '..A.A...',
      '...A....',
      '........'
    ]
  };

  /* Bright core, mid body, deep edge -- the three letters every shape uses. */
  const TINTS = {
    fire: ['#fff0a8', '#e8743b', '#8a3b2a'],
    ice: ['#ffffff', '#a8e4ff', '#2f6fa8'],
    lightning: ['#ffffff', '#fff0a8', '#f2c14e'],
    poison: ['#a3e86b', '#5cbf62', '#1b4436'],
    water: ['#a8e4ff', '#4fb3e0', '#16324f'],
    earth: ['#b98d5c', '#8a6340', '#2e2018'],
    leaf: ['#a3e86b', '#2f7d4f', '#1b4436'],
    dark: ['#c86ee0', '#7f45b8', '#1e0f2a'],
    holy: ['#ffffff', '#fff0a8', '#8a7440'],
    star: ['#ffffff', '#ffd56b', '#f2c14e'],
    cute: ['#ffffff', '#ff99c8', '#c86ee0'],
    magic: ['#ffffff', '#a8e4ff', '#c86ee0']
  };

  const cache = {};

  function get(shape, element) {
    const rows = SHAPES[shape];
    if (!rows) return null;
    const tint = TINTS[element] || TINTS.fire;
    const key = shape + ':' + (TINTS[element] ? element : 'fire');
    if (!cache[key]) {
      cache[key] = A.makeSprite(rows, { A: tint[0], B: tint[1], C: tint[2] }, FX_D);
    }
    return cache[key];
  }

  DS.FXArt = {
    D: FX_D,
    shapes: SHAPES,
    tints: TINTS,
    get: get,
    has: function (shape) { return !!SHAPES[shape]; }
  };
})(window.DS);
